# Generated by Django 3.1.7 on 2021-07-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=256)),
                ('translated_to_language', models.CharField(choices=[('EN', 'English'), ('MA', 'Marathi'), ('HI', 'Hindi'), ('GJ', 'Gujrati')], default='EN', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('N', 'New'), ('IP', 'In-Process'), ('C', 'Complete')], default='N', max_length=20)),
                ('translated_text', models.CharField(choices=[('EN', 'English'), ('MA', 'Marathi'), ('HI', 'Hindi'), ('GJ', 'Gujrati')], default='EN', max_length=20)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
